import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "tr" | "en" | "de";

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  tr: {
    home: "Ana Sayfa",
    brochures: "Broşürler",
    pricing: "Fiyatlandırma",
    contact: "İletişim",
    specialDesign: "Özel Tasarım",
    getStarted: "Hemen Başla",
    heroTitle: "Market İndirimlerinizi Saniyeler İçinde Dijital Broşürlere Dönüştürün",
    heroSubtitle: "Tasarım bilgisi gerekmez. Ürünleri seçin, şablon belirleyin ve anında paylaşın.",
    pricingSubtitle: "İşletmenizin ölçeğine uygun paketlerimizden birini seçin.",
    contactSubtitle: "Sorularınız için bizimle iletişime geçin.",
    sendMessage: "Bize mesaj gönderin",
    fullName: "Ad Soyad",
    phoneNumber: "Telefon Numarası",
    companyName: "Şirket Adı",
    industry: "Sektör",
    howCanWeHelp: "Size nasıl yardımcı olabiliriz?",
    sending: "Gönderiliyor...",
    send: "Gönder",
    howItWorks: "Nasıl Çalışır?",
    howItWorksSubtitle: "Dijital pazarlamanın gücünü, hızı ve esnekliği e-Brochure ile keşfedin.",
    step1Title: "Anında Dijital Kampanyalar",
    step1Desc: "Geleneksel broşürler yerine saniyeler içinde dijital kampanyalar oluşturun. Tasarım bilgisi gerekmeden anında başlayın.",
    step2Title: "Zengin Ürün Kataloğu",
    step2Desc: "Geniş ürün havuzundan dilediğiniz ürünleri seçin. İçeriği dinamik olarak güncelleyerek her zaman güncel kalın.",
    step3Title: "Esnek Broşür Oluşturucu",
    step3Desc: "Yerleşim, ürün konumlandırma ve görsel hiyerarşiyi tamamen markanıza özel şekilde özelleştirin.",
    step4Title: "Özelleştirilebilir Şablonlar",
    step4Desc: "Hazır şablonları düzenleyin, yeniden düzenleyin ve tekrar kullanın. Profesyonel görünümü koruyun.",
    step5Title: "Tenant Mimarisi ile Yönetim",
    step5Desc: "Birden fazla şube, ekip ve kampanyayı tek bir merkezden, güvenli ve düzenli bir şekilde yönetin.",
    step6Title: "Saniyeler İçinde Paylaşın",
    step6Desc: "Hazırladığınız broşürü Instagram, Facebook ve WhatsApp gibi platformlarda anında yayınlayın.",
    step7Title: "Tanıtım ve Reklam Gücü",
    step7Desc: "Broşürlerinizi doğrudan sosyal medya reklamlarına dönüştürün ve hedef kitlenize anında ulaşın.",
    step8Title: "Kampanya Performans Analizi",
    step8Desc: "Erişim, etkileşim ve kullanıcı verilerini takip ederek veriye dayalı kararlar alın.",
    step9Title: "Modern, Hızlı ve Kolay",
    step9Desc: "Her cihazdan erişilebilir, kullanıcı dostu ve ultra hızlı bir deneyimle karmaşıklığa son verin.",
    overallGoal: "Genel Hedefimiz",
    overallGoalDesc: "e-Brochure, geleneksel basılı broşürlerin yerini dinamik, dijital ve ölçülebilir bir pazarlama çözümüyle doldurur. İşletmelerin zahmetsizce kampanya oluşturmasına, paylaşmasına, reklamını yapmasına ve analiz etmesine yardımcı olur.",
    seeExamples: "Örnekleri Gör",
    trustedBy: "2.000'den fazla pazarlamacı tarafından güveniliyor",
    aiPowered: "Yapay Zeka Destekli Düzenler",
    freeTrial: "Ücretsiz Başlayın",
    ctaTitle: "İlk dijital broşürünüzü başlatmaya hazır mısınız?",
    ctaSubtitle: "Bugün daha iyi deneyimler oluşturan binlerce pazarlamacıya katılın.",
    benefits: "Faydaları",
    benefitsSubtitle: "e-Brochure kullanmanın geleneksel broşürlere göre temel avantajlarını keşfedin.",
    dashboardUsage: "Dashboard Kullanımı",
    brochureCreation: "Broşür Oluşturma",
    templateCustomization: "Şablon Özelleştirme",
    publishingPromotion: "Yayınlama ve Tanıtım",
    watchTutorial: "Eğitimi İzle",
    howItWorksDetailedSubtitle: "e-Brochure'u nasıl kullanacağınızı adım adım öğrenin.",
    feature1: "1 Aktif Broşür",
    feature2: "Temel Analizler",
    feature3: "Standart Şablonlar",
    feature4: "e-Brochure Markalaması",
    feature5: "10 Aktif Broşür",
    feature6: "Gelişmiş Analizler",
    feature7: "Premium Şablonlar",
    feature8: "Markasız Kullanım",
    feature9: "Özel Alan Adı",
    feature10: "Öncelikli Destek",
    feature11: "Sınırsız Broşür",
    feature12: "Gerçek Zamanlı Isı Haritaları",
    feature13: "Özel Tasarım Sistemi",
    feature14: "API Erişimi",
    feature15: "SSO ve Gelişmiş Güvenlik",
    feature16: "Özel Başarı Yöneticisi",
    missing1: "Özel Alan Adı",
    missing2: "Ekip İşbirliği",
    missing3: "API Erişimi",
    whyDigital: "Neden Dijital?",
    whyDigitalSubtitle: "Baskı maliyetlerini durdurun. Etkileşimi takip etmeye başlayın.",
    feature: "Özellik",
    traditionalPdf: "Geleneksel PDF",
    productionCost: "Üretim Maliyeti",
    distributionSpeed: "Dağıtım Hızı",
    analytics: "Analizler",
    ecoFriendly: "Çevre Dostu",
    mobileFriendly: "Mobil Uyumlu",
    lowCost: "Düşük Maliyet",
    instantPublishing: "Anında Yayınlama",
    realTimeUpdates: "Gerçek Zamanlı Güncellemeler",
    testimonialsTitle: "Pazarlama Ekipleri Tarafından Seviliyor",
    trustedBrands: "GÜVENEN MARKALAR",
    footerDesc: "Statik belgeleri etkileşimli dijital deneyimlere dönüştürüyoruz. Dijital pazarlamanın geleceği burada başlıyor.",
    product: "Ürün",
    company: "Şirket",
    legal: "Yasal",
    features: "Özellikler",
    templates: "Şablonlar",
    caseStudies: "Başarı Hikayeleri",
    aboutUs: "Hakkımızda",
    careers: "Kariyer",
    blog: "Blog",
    privacyPolicy: "Gizlilik Politikası",
    termsOfService: "Kullanım Şartları",
    cookiePolicy: "Çerez Politikası",
    allRightsReserved: "Tüm hakları saklıdır.",
    madeWith: "Modern pazarlamacılar için ❤️ ile yapıldı.",
    inspirationGallery: "İlham Galerisi",
    gallerySubtitle: "Yüksek performanslı dijital broşür koleksiyonumuza göz atın ve nelerin mümkün olduğunu görün.",
    searchExamples: "Örnekleri ara...",
    all: "Hepsi",
    viewDemo: "Demoyu Gör",
    preview: "Önizleme",
    monthly: "Aylık",
    yearly: "Yıllık",
    mostPopular: "En Popüler",
    starter: "Başlangıç",
    professional: "Profesyonel",
    enterprise: "Kurumsal",
    starterDesc: "Bireyler ve küçük testler için mükemmel.",
    professionalDesc: "Büyüyen işletmeler ve pazarlamacılar için.",
    enterpriseDesc: "Ajanslar ve büyük ekipler için tam güç.",
    requestCustomTemplate: "Özel Şablon Talep Et",
    customTemplateDesc: "Markanız için özel bir düzene mi ihtiyacınız var? Vizyonunuzu anlatın, tasarım ekibimiz sizin için özel bir şablon oluştursun.",
    yourName: "Adınız",
    emailAddress: "E-posta Adresi",
    describeIdealTemplate: "İdeal Şablonunuzu Tanımlayın",
    templatePrompt: "Renk şeması, düzen yapısı (ızgara vs liste), içerik türleri (video, metin ağırlıklı, resim ağırlıklı) ve gereken özel işlevler hakkında ayrıntıları ekleyin.",
    submitDesignRequest: "Tasarım Talebini Gönder",
    submitting: "Gönderiliyor...",
    emailUs: "Bize E-posta Gönderin",
    callUs: "Bizi Arayın",
    visitUs: "Bizi Ziyaret Edin",
    highCost: "Yüksek ($$$)",
    daysWeeks: "Günler/Haftalar",
    none: "Yok",
    paperWaste: "Kağıt Atığı",
    pinchZoom: "Pinch & Zoom ❌",
    nativeFeel: "Native Hisset ✅",
    digital100: "%100 Dijital",
    realTime: "Gerçek zamanlı",
    instant: "Anında",
    howItWorksStep1Title: "Hızlı Kurulum",
    howItWorksStep1Desc: "Dashboard üzerinden saniyeler içinde hesabınızı yapılandırın.",
    howItWorksStep2Title: "Broşür Oluşturma",
    howItWorksStep2Desc: "Ürünlerinizi ekleyin ve şablonunuzu seçin.",
    howItWorksStep3Title: "Özelleştirme",
    howItWorksStep3Desc: "Renkleri ve düzeni markanıza göre uyarlayın.",
    howItWorksStep4Title: "Yayınlama",
    howItWorksStep4Desc: "Tek tıkla tüm platformlarda paylaşın.",
  },
  en: {
    home: "Home",
    brochures: "Brochures",
    pricing: "Pricing",
    contact: "Contact",
    specialDesign: "Special Design",
    getStarted: "Get Started",
    heroTitle: "Convert Your Market Discounts into Digital Brochures in Seconds",
    heroSubtitle: "No design knowledge required. Select products, choose a template, and share instantly.",
    pricingSubtitle: "Choose one of our packages that suits your business scale.",
    contactSubtitle: "Contact us for your questions.",
    sendMessage: "Send us a message",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    companyName: "Company Name",
    industry: "Industry",
    howCanWeHelp: "How can we help?",
    sending: "Sending...",
    send: "Send Message",
    howItWorks: "How It Works",
    howItWorksSubtitle: "Discover the power, speed, and flexibility of digital marketing with e-Brochure.",
    step1Title: "Instant Digital Campaigns",
    step1Desc: "Create digital brochures in seconds instead of traditional flyers. Start instantly without design knowledge.",
    step2Title: "Rich Product Catalog",
    step2Desc: "Choose products from a wide pool. Update content dynamically to stay current at all times.",
    step3Title: "Flexible Brochure Builder",
    step3Desc: "Fully customize layouts, product positioning, and visual hierarchy for your brand.",
    step4Title: "Customizable Templates",
    step4Desc: "Edit, rearrange, and reuse ready templates. Maintain a professional look consistently.",
    step5Title: "Organized Management with Tenant Architecture",
    step5Desc: "Manage multiple branches, teams, and campaigns securely and orderly from a single center.",
    step6Title: "Share in Seconds",
    step6Desc: "Instantly publish your brochure on platforms like Instagram, Facebook, and WhatsApp.",
    step7Title: "Promotion and Advertising Power",
    step7Desc: "Turn your brochures directly into social media ads and reach your target audience immediately.",
    step8Title: "Campaign Performance Analysis",
    step8Desc: "Track reach, engagement, and user data to make data-driven decisions.",
    step9Title: "Modern, Fast, and Easy to Use",
    step9Desc: "Eliminate complexity with an ultra-fast, user-friendly experience accessible from any device.",
    overallGoal: "Our Overall Goal",
    overallGoalDesc: "e-Brochure replaces traditional printed brochures with a dynamic, digital, and measurable marketing solution. It helps businesses create, share, advertise, and analyze campaigns effortlessly.",
    seeExamples: "See Examples",
    trustedBy: "Trusted by over 2,000 marketers",
    aiPowered: "AI-Powered Layouts",
    freeTrial: "Start for Free",
    ctaTitle: "Ready to launch your first digital brochure?",
    ctaSubtitle: "Join thousands of marketers creating better experiences today.",
    benefits: "Benefits",
    benefitsSubtitle: "Discover the key benefits of using e-Brochure instead of traditional brochures.",
    dashboardUsage: "Dashboard Usage",
    brochureCreation: "Brochure Creation",
    templateCustomization: "Template Customization",
    publishingPromotion: "Publishing & Promotion",
    watchTutorial: "Watch Tutorial",
    howItWorksDetailedSubtitle: "Learn how to use e-Brochure step by step.",
    feature1: "1 Active Brochure",
    feature2: "Basic Analytics",
    feature3: "Standard Templates",
    feature4: "e-Brochure Branding",
    feature5: "10 Active Brochures",
    feature6: "Advanced Analytics",
    feature7: "Premium Templates",
    feature8: "No Branding",
    feature9: "Custom Domain",
    feature10: "Priority Support",
    feature11: "Unlimited Brochures",
    feature12: "Real-time Heatmaps",
    feature13: "Custom Design System",
    feature14: "API Access",
    feature15: "SSO & Advanced Security",
    feature16: "Dedicated Success Manager",
    missing1: "Custom Domain",
    missing2: "Team Collaboration",
    missing3: "API Access",
    whyDigital: "Why Digital?",
    whyDigitalSubtitle: "Stop printing costs. Start tracking engagement.",
    feature: "Feature",
    traditionalPdf: "Traditional PDF",
    productionCost: "Production Cost",
    distributionSpeed: "Distribution Speed",
    analytics: "Analytics",
    ecoFriendly: "Eco-Friendly",
    mobileFriendly: "Mobile Friendly",
    lowCost: "Low Cost",
    instantPublishing: "Instant Publishing",
    realTimeUpdates: "Real-time Updates",
    testimonialsTitle: "Loved by Marketing Teams",
    trustedBrands: "TRUSTED BRANDS",
    footerDesc: "We transform static documents into interactive digital experiences. The future of digital marketing starts here.",
    product: "Product",
    company: "Company",
    legal: "Legal",
    features: "Features",
    templates: "Templates",
    caseStudies: "Case Studies",
    aboutUs: "About Us",
    careers: "Careers",
    blog: "Blog",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    cookiePolicy: "Cookie Policy",
    allRightsReserved: "All rights reserved.",
    madeWith: "Made with ❤️ for modern marketers.",
    inspirationGallery: "Inspiration Gallery",
    gallerySubtitle: "Browse our collection of high-performing digital brochures and see what's possible.",
    searchExamples: "Search examples...",
    all: "All",
    viewDemo: "View Demo",
    preview: "Preview",
    monthly: "Monthly",
    yearly: "Yearly",
    mostPopular: "Most Popular",
    starter: "Starter",
    professional: "Professional",
    enterprise: "Enterprise",
    starterDesc: "Perfect for individuals and small tests.",
    professionalDesc: "For growing businesses and marketers.",
    enterpriseDesc: "Full power for agencies and large teams.",
    requestCustomTemplate: "Request Custom Template",
    customTemplateDesc: "Need a specific layout for your brand? Describe your vision and our design team will build a custom template for you.",
    yourName: "Your Name",
    emailAddress: "Email Address",
    describeIdealTemplate: "Describe Your Ideal Template",
    templatePrompt: "Include details about color scheme, layout structure (grid vs list), types of content (video, text heavy, image heavy), and any specific functionality needed.",
    submitDesignRequest: "Submit Design Request",
    submitting: "Submitting...",
    emailUs: "Email Us",
    callUs: "Call Us",
    visitUs: "Visit Us",
    highCost: "High ($$$)",
    daysWeeks: "Days/Weeks",
    none: "None",
    paperWaste: "Paper Waste",
    pinchZoom: "Pinch & Zoom ❌",
    nativeFeel: "Native Feel ✅",
    digital100: "100% Digital",
    realTime: "Real-time",
    instant: "Instant",
    howItWorksStep1Title: "Quick Setup",
    howItWorksStep1Desc: "Configure your account in seconds via the dashboard.",
    howItWorksStep2Title: "Create Brochure",
    howItWorksStep2Desc: "Add your products and choose your template.",
    howItWorksStep3Title: "Customization",
    howItWorksStep3Desc: "Tailor colors and layout to your brand.",
    howItWorksStep4Title: "Publishing",
    howItWorksStep4Desc: "Share across all platforms with one click.",
  },
  de: {
    home: "Startseite",
    brochures: "Broschüren",
    pricing: "Preise",
    contact: "Kontakt",
    specialDesign: "Sonderanfertigung",
    getStarted: "Jetzt loslegen",
    heroTitle: "Verwandeln Sie Ihre Marktrabatte in Sekundenschnelle in digitale Broschüren",
    heroSubtitle: "Keine Designkenntnisse erforderlich. Produkte auswählen, Vorlage wählen und sofort teilen.",
    pricingSubtitle: "Wählen Sie eines unserer Pakete, das zu Ihrer Unternehmensgröße passt.",
    contactSubtitle: "Kontaktieren Sie uns bei Fragen.",
    sendMessage: "Schicken Sie uns eine Nachricht",
    fullName: "Vollständiger Name",
    phoneNumber: "Telefonnummer",
    companyName: "Name der Firma",
    industry: "Branche",
    howCanWeHelp: "Wie können wir helfen?",
    sending: "Senden...",
    send: "Nachricht senden",
    howItWorks: "Wie es funktioniert?",
    howItWorksSubtitle: "Entdecken Sie mit e-Brochure die Kraft, Geschwindigkeit und Flexibilität des digitalen Marketings.",
    step1Title: "Sofortige digitale Kampagnen",
    step1Desc: "Erstellen Sie digitale Broschüren in Sekunden statt herkömmlicher Flyer. Starten Sie sofort ohne Designkenntnisse.",
    step2Title: "Reichhaltiger Produktkatalog",
    step2Desc: "Wählen Sie Produkte aus einem großen Pool. Aktualisieren Sie Inhalte dynamisch, um jederzeit aktuell zu bleiben.",
    step3Title: "Flexibler Broschüren-Ersteller",
    step3Desc: "Passen Sie Layouts, Produktpositionierung und visuelle Hierarchie vollständig für Ihre Marke an.",
    step4Title: "Anpassbare Vorlagen",
    step4Desc: "Bearbeiten, ordnen und verwenden Sie fertige Vorlagen wieder. Behalten Sie konsistent ein professionelles Aussehen bei.",
    step5Title: "Organisiertes Management mit Tenant-Architektur",
    step5Desc: "Verwalten Sie mehrere Filialen, Teams und Kampagnen sicher und ordentlich von einem einzigen Zentrum aus.",
    step6Title: "In Sekundenschnelle teilen",
    step6Desc: "Veröffentlichen Sie Ihre Broschüre sofort auf Plattformen wie Instagram, Facebook und WhatsApp.",
    step7Title: "Werbe- und Werbekraft",
    step7Desc: "Verwandeln Sie Ihre Broschüren direkt in Social-Media-Anzeigen und erreichen Sie sofort Ihre Zielgruppe.",
    step8Title: "Kampagnen-Performance-Analyse",
    step8Desc: "Verfolgen Sie Reichweite, Engagement und Nutzerdaten, um datengesteuerte Entscheidungen zu treffen.",
    step9Title: "Modern, schnell und einfach zu bedienen",
    step9Desc: "Beseitigen Sie Komplexität mit einem ultraschnellen, benutzerfreundlichen Erlebnis, das von jedem Gerät aus zugänglich ist.",
    overallGoal: "Unser Gesamtziel",
    overallGoalDesc: "e-Brochure ersetzt herkömmliche gedruckte Broschüren durch eine dynamische, digitale und messbare Marketinglösung. Es hilft Unternehmen, Kampagnen mühelos zu erstellen, zu teilen, zu bewerben und zu analysieren.",
    seeExamples: "Beispiele ansehen",
    trustedBy: "Über 2.000 Marketingspezialisten vertrauen uns",
    aiPowered: "KI-gestützte Layouts",
    freeTrial: "Kostenlos starten",
    ctaTitle: "Bereit, Ihre erste digitale Broschüre zu erstellen?",
    ctaSubtitle: "Schließen Sie sich tausenden Marketingspezialisten an, die heute bessere Erlebnisse schaffen.",
    whyDigital: "Warum digital?",
    whyDigitalSubtitle: "Schluss mit Druckkosten. Starten Sie das Tracking von Interaktionen.",
    feature: "Merkmal",
    traditionalPdf: "Herkömmliches PDF",
    productionCost: "Produktionskosten",
    distributionSpeed: "Versandgeschwindigkeit",
    analytics: "Analysen",
    ecoFriendly: "Umweltfreundlich",
    mobileFriendly: "Mobiloptimiert",
    lowCost: "Niedrige Kosten",
    instantPublishing: "Sofortige Veröffentlichung",
    realTimeUpdates: "Echtzeit-Updates",
    testimonialsTitle: "Beliebt bei Marketing-Teams",
    trustedBrands: "MARKEN, DIE UNS VERTRAUEN",
    footerDesc: "Wir verwandeln statische Dokumente in interaktive digitale Erlebnisse. Die Zukunft des digitalen Marketings beginnt hier.",
    product: "Produkt",
    company: "Unternehmen",
    legal: "Rechtliches",
    features: "Eigenschaften",
    templates: "Vorlagen",
    caseStudies: "Fallstudien",
    aboutUs: "Über uns",
    careers: "Karriere",
    blog: "Blog",
    privacyPolicy: "Datenschutzrichtlinie",
    termsOfService: "Nutzungsbedingungen",
    cookiePolicy: "Cookie-Richtlinie",
    allRightsReserved: "Alle Rechte vorbehalten.",
    madeWith: "Mit ❤️ für moderne Vermarkter gemacht.",
    inspirationGallery: "Inspirationsgalerie",
    gallerySubtitle: "Durchsuchen Sie unsere Sammlung hochperformanter digitaler Broschüren und sehen Sie, was möglich ist.",
    searchExamples: "Beispiele suchen...",
    all: "Alle",
    viewDemo: "Demo ansehen",
    preview: "Vorschau",
    monthly: "Monatlich",
    yearly: "Jährlich",
    mostPopular: "Beliebteste",
    starter: "Starter",
    professional: "Professional",
    enterprise: "Enterprise",
    starterDesc: "Perfekt für Einzelpersonen und kleine Tests.",
    professionalDesc: "Für wachsende Unternehmen und Vermarkter.",
    enterpriseDesc: "Volle Power für Agenturen und große Teams.",
    requestCustomTemplate: "Individuelle Vorlage anfordern",
    customTemplateDesc: "Benötigen Sie ein spezielles Layout für Ihre Marke? Beschreiben Sie Ihre Vision ve unser Designteam erstellt eine individuelle Vorlage für Sie.",
    yourName: "Ihr Name",
    emailAddress: "E-Mail-Adresse",
    describeIdealTemplate: "Beschreiben Sie Ihre ideale Vorlage",
    templatePrompt: "Geben Sie Details zu Farbschema, Layoutstruktur (Raster vs. Liste), Inhaltstypen (Video, textlastig, bildlastig) und erforderlichen speziellen Funktionen an.",
    submitDesignRequest: "Designanfrage senden",
    submitting: "Senden...",
    emailUs: "Schreiben Sie uns",
    callUs: "Rufen Sie uns an",
    visitUs: "Besuchen Sie uns",
    highCost: "Hoch ($$$)",
    daysWeeks: "Tage/Wochen",
    none: "Keine",
    paperWaste: "Papierverschwendung",
    pinchZoom: "Pinch & Zoom ❌",
    nativeFeel: "Native Feel ✅",
    digital100: "100% Digital",
    realTime: "Echtzeit",
    instant: "Sofort",
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem("lang");
      return (saved as Language) || "tr";
    }
    return "tr";
  });

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
